spring:
  application:
    name: demo6
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

---

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: user
    password: 1234
  config:
    activate:
      on-profile: test
  flyway:
    enabled: true
    baseline-on-migrate: false
